name: Brew Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    
    - name: Install Deployment API CLI
      run: |
        wget https://github.com/mgudmund/deployment-api-cli/releases/download/v1.0-alpha/deployment-api-cli-v1.0-alpha.x86_64-linux.tar.gz 
        tar -zxvf deployment-api-cli-v1.0-alpha.x86_64-linux.tar.gz
        sudo mv deployment-api-cli /usr/bin/

    - name: Test
      run: deployment-api-cli help

   
