name: Brew Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    
    - name: Tap
      run: brew install mgudmund/deployment-api-cli

    - name: Test
      run: deployment-api-cli help

   
