name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.11
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run Gosec Security Scanner
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get github.com/securego/gosec/cmd/gosec
        gosec ./...

    - name: Build
      run: go build -v .

    - name: Unit Test
      run: go test -v .

   # - name: Black Duck Scan
   #   uses: blackducksoftware/github-action@2.0.0
   #   with:
   #     args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true'
    
   # - uses: actions/upload-artifact@v2
   #   with:
   #       name: BlackDuck Report
   #       path: ./*RiskReport*
    
         
